CREATE DATABASE master;


SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";



CREATE TABLE IF NOT EXISTS `tb_pessoa` (
  `ID_PESSOA` int(8) NOT NULL AUTO_INCREMENT,
  `NOME_PESSOA` varchar(255) NOT NULL,
  `EMAIL_PESSOA` varchar(200) NOT NULL,
  `GRADUACAO_PESSOA` varchar(30) NOT NULL,
  `SEXO_PESSOA` varchar(10) NOT NULL,
  `FORMADO_PESSOA` tinyint(1) NOT NULL,
  PRIMARY KEY (`ID_PESSOA`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=24 ;



